sonar.projectKey=switcherapi_switcher-client-go
sonar.projectName=switcher-client-go
sonar.organization=switcherapi
sonar.projectVersion=1.0.0
sonar.links.homepage=https://github.com/switcherapi/switcher-client-go

sonar.sources=.
sonar.exclusions=**/*_test.go,coverage/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=coverage/**

sonar.language=go
sonar.go.coverage.reportPaths=coverage.out
